# Generated by Django 5.2.6 on 2025-09-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0002_alter_blockedip_id_alter_requestlog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
